version: '3'
services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './tmp/redis:/bitnami'
  db:
    container_name: postgres
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/urless/backend
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      RAILS_DATABASE_HOST: "db"
  frontend:
    container_name: frontend
    image: "node:14-alpine"
    user: "node"
    working_dir: /urless/frontend
    volumes:
      - ./frontend:/urless/frontend
    command: "yarn dev"
    depends_on:
      - backend
    ports:
      - 8080:8080
